apiVersion: v1
kind: Service
metadata:
  name: react-app-service
  namespace: ${{ secrets.KUBE_NAMESPACE || 'default' }}
spec:
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # Use LoadBalancer to expose externally, or ClusterIP for internal access
  